### ISSUE TITLE
Permitir que entidades cadastrem vagas

### ISSUE THREAD

**Issue by regiov** [regiov/voluntarios#14]

**Comment by Diogojlq** [comment]
Olá @regiov, boa tarde. Achei essa issue bem interessante, gostaria de trabalhar nela.

**Comment by regiov** [comment]
Fala @Diogojlq, essa você escolheu a dedo, hein? Faz tempo que ela está no topo das prioridades, mas como tenho a sensação de que vai ser bem complexo, nunca tive tempo suficiente pra me dedicar a ela. Quem sabe agora? Se você quiser mesmo, vamos em frente. Só que nesse caso vamos ter que trabalhar juntos, e pensar muito bem antes de sair implementando. Talvez produzir alguma especificação antes, o que acha?

**Comment by Diogojlq** [comment]
Acredito que seja o correto sim, deixar as coisas bem definidas antes de começar.
Não sei se você tem em mente algum site ou ferramenta, mas que tal começar definindo o modelo de "vaga" ? Imagino que deva ter pelo menos descrição, título/função/cargo, data de publicação, local...mas tenho certeza que deve ter coisas mais específicas que deveriam ser incluídas.

Também pensei em já criar um template para a vaga, para quando o usuário entrar em uma vaga específica, e uma para a lista de vagas.

**Comment by regiov** [comment]
Legal, @Diogojlq então vamos em frente. Penso que o correto seja definirmos o modelo mesmo, e só depois partir para views e templates. Não sei a melhor maneira de trabalharmos juntos nisso. Poderia ser ou por aqui mesmo, ou talvez no wiki do projeto aqui no github. Alguma outra sugestão? Se for no wiki, preciso só saber se você consegue editar páginas lá.

**Comment by regiov** [comment]
O que torna essa issue particularmente difícil, é que não faz muito sentido disponibilizar um esquema de vagas sem também ter uma forma de permitir que as pessoas se inscrevam na vaga, e que haja pelo menos algum jeito da entidade gerenciar as inscrições. Além disso, depois preciso compartilhar com você algumas ideias do contexto em que surge a necessidade de anunciar vagas... Talvez a gente nem precise abarcar toda a complexidade que estou imaginando no momento, mas é importante não perder de vista o panorama geral.

**Comment by regiov** [comment]
Veja @Diogojlq : https://github.com/regiov/voluntarios/wiki/Planejamento

**Comment by Diogojlq** [comment]
Olá Renato, desculpa a demora, tive alguns imprevistos. 
Não tenho acesso a editar a wiki, mas lá parece ser uma boa opção. Eu ia sugerir o Lucid Chart pela possibilidade de criar fluxogramas, mas parece ser possível na wiki.

Pelo que entendi do planejamento, a entidade vai ter um projeto, que vai ter uma atividade, e dentro do escopo de cada tipo de atividade teremos o processo seletivo, que vai ter um anúncio para a vaga, que receberá inscrições. E quando estiver em um projeto, o voluntário terá um true or false em AlocacaoRecursoHumanoEmAtividade. Seria isso ?

A partir daí precisamos definir como a entidade vai gerenciar essas inscrições, e como vai recebê-las. O Google Forms tem uma API sim(https://developers.google.com/forms/api/quickstart/python), porém alguns passos para ativá-la no Google Cloud e autenticar acredito que seja melhor você mesmo dar uma olhada, por envolver questões de segurança.

Sobre usar a ferramenta para trabalho remunerado, acredito que seria melhor deixar como está, bastando que a pessoa remunerada cadastre um perfil de voluntário, talvez eu não tenha entendido a profundidade da questão aqui, mas pelo que entendi o problema de ser remunerado seria ter uma pessoa como voluntária porém não ser exatamente trabalho voluntário(?). Nesse caso creio que poderiamos fazer um outro cadastro(outro modelo), como o de voluntário, mas com algumas mudanças, e pedir para o usuário se cadastrar para se inscrever em um trabalho remunerado.

Para permitir projetos de mais de uma entidade, acho que seria interessante ter um modelo como "projeto colaborativo", e incorporar nele o que seja necessário.

**Comment by regiov** [comment]
Diogo, acabei de incluir você como colaborador aqui no repositório. Assim que aceitar o convite, por favor teste novamente a edição de páginas no wiki.

Essa parte de projetos & atividades ainda tenho algumas dúvidas. O exemplo que coloquei lá do clipping de notícias se encaixa bem nisso, mas e se pensarmos na parte de TI do Voluntários? Você chegou aqui porque viu o texto na página "junte-se ao Voluntários" e clicou no link pra preencher o formulário. O que temos feito na parte de TI é ter uma espécie de processo seletivo contínuo, independente de projetos e atividades. Se bem que futuramente até poderíamos pensar em anunciar vagas para issues específicas aqui no github, que não deixam de ser atividades, certo? Isso poderia ser interessante experimentar. Mas o ponto em que quero chegar é que talvez o processo seletivo não precise obrigatoriamente estar vinculado a um projeto/atividade. Se a essência do raciocínio estiver correta, vou tentar colocar mais detalhes lá no wiki sobre como tudo isso poderia ser implementado na prática.

O trâmite entre inscrição e alocação de recurso humano em atividade (o que também não precisaria ser obrigatório) ainda não está muito claro pra mim.

Quanto àquelas questões em "modo viagem", melhor não nos preocuparmos com aquilo no momento. Coloquei lá só pra não esquecer essas ideias.

**Comment by Diogojlq** [comment]
Boa tarde @regiov, tem alguma sugestão para o modelo "Iniciativa" ? Já criei o item no menu lateral, estou tentando pegar o id da entidade para retornar a lista de iniciativas da entidade, mas ainda não criei esse modelo.

**Comment by regiov** [comment]
Oi @Diogojlq, legal que você tá empolgado, mas quando as alterações são muito grandes é importante a gente planejar bem antes pra diminuir o risco de retrabalho. Pessoalmente ainda tenho várias dúvidas, e fico pensando se não seria melhor desvincularmos o “processo seletivo” de toda a complexidade de gerenciamento de projetos. Quando digo desvincular quero dizer não exigir que haja esse vínculo. Ou seja, quem quiser pode criar um processo seletivo a qualquer momento sem precisar cadastrar tudo que existe por trás dele. Nesse sentido, talvez seja legal darmos uma olhada no linkedin, que acredito ser o maior site de recrutamento hoje em dia pra vermos como funciona o processo seletivo por lá.

Não que isso invalide a ideia de gerenciamento de projetos, que acho que devemos continuar tendo em vista.

O que acha?

**Comment by regiov** [comment]
De qualquer forma, coloquei no wiki uma ideia inicial de modelo para iniciativa, mas não sei se lá é o melhor lugar e tb não consegui formatar direito com o celular..,

**Comment by Diogojlq** [comment]
Entendo, então no caso de desvincular o processo seletivo, um voluntário ou usuário poderia abrir um processo seletivo ? Ou até mesmo alguém que não esteja cadastrado no site ?

No LinkedIn especificamente, é só clicar em "publicar vaga", o que te redireciona a um formulário, que possui os campos:
-Cargo
-Empresa
-Local de trabalho
-Local da vaga
-Tipo de vaga(estágio, tempo integral etc.)

Quando esses dados são inseridos e enviados o site redireciona novamente para inserir uma descrição e competências.
No nosso caso poderíamos fazer de forma semelhante em uma mesma página, trocando campos como "empresa" por "entidade".

No final também tem uma página para definir a forma de gerenciar as candidaturas, por email ou site externo. No nosso caso acho que não seria necessário, afinal vamos lidar com isso apenas internamente no site, certo ? 
E como fica a questão dos formulários do Google ? Seria no caso da empresa possuir um formulário próprio no Google Forms e poder vincular ao processo seletivo ou a vaga ?

Não ficou muito claro também a parte dos modelos de processo seletivo, atividade e vaga. Será que não faria sentido se o processo seletivo tiver o anúncio de vaga, e a vaga tiver a "atividade" ? Afinal o processo seletivo pode ser para uma iniciativa que envolva mais de uma atividade, fazendo-se necessário abrir dois processos seletivos para a mesma iniciativa, pois todas as vagas do processo seletivo seriam da atividade do processo seletivo, e se esse raciocínio estiver correto para mim faria mais sentido da forma que eu mencionei.
Eu até vejo o motivo de ter a atividade como base, mas enfim, acho que talvez eu que precise entender melhor como você está pensando.

**Comment by regiov** [comment]
Bom, vamos lá… sobre o processo seletivo, sempre quem vai criar é um usuário cadastrado no site e responsável por uma ou mais entidades. O processo seletivo sempre é de uma entidade, e pra mim está claro que podemos criar um novo menu lateral chamado “processos seletivos” no gerenciamento de uma entidade.

O que eu quis dizer antes é que ao criar um novo processo seletivo não precisamos obrigar o usuário a definir todas as iniciativas/atividades que estão por trás. Ou seja, podemos perfeitamente implementar primeiro a parte de processos seletivos - que está mais diretamente ligada a essa issue, e mais pra frente implementamos o gerenciamento de iniciativas/atividades, permitindo futuramente linkar as 2 coisas (ao criar processos seletivos, possibilitar escolher de forma não obrigatória iniciativas/atividades relacionadas).

**Comment by regiov** [comment]
Continuando… sim, concordo que podemos começar da forma mais simples, com uma só página para cadastro do processo seletivo. E sim, vamos lidar com ele apenas internamente no site.

O link para o formulário do google pode ser um campo opcional no modelo processo seletivo, e ele seria exibido apenas depois que o voluntário se inscrever.

A grande dúvida é: como fazemos para buscar as respostas no google via api para vincular a resposta a alguma inscrição? Se isso for possível, seria fantástico, pois ao visualizar as inscrições, as entidades vão conseguir saber quem já respondeu o formulário e como acessar a resposta.

**Comment by regiov** [comment]
Quanto aos modelos, processo seletivo e vaga pra mim são a mesma coisa. Prefiro o termo processo seletivo (mesmo que no site a gente decida exibir como “vaga” para os usuários).

Sugiro deixarmos os modelos iniciativa/atividades para depois.

Anuncio de vaga não sei se vamos usar. Acho que não, mas ainda não tenho certeza. Sugiro nos concentrarmos em processo seletivo e inscrição em processo seletivo, sendo que fica faltando definir como serão gerenciadas as inscrições… Isso ainda não pensei.

**Comment by Diogojlq** [comment]
Olá @regiov, desculpe a demora para retornar, dias bem corridos por aqui, estou ansioso para poder começar a trabalhar na prática nessa issue.

Criei o item "processos seletivos" no menu de gerenciamento de entidade e uma página que ainda está vazia.

Em relação ao formulário, sim, tem como resgatar as respostas via API, tanto todas as respostas de um formulário como respostas específicas, pelo que encontrei nessa documentação : https://developers.google.com/forms/api/guides/retrieve-forms-responses#:~:text=The%20Google%20Forms%20API%20lets,the%20end%2Duser%20form%20responses.
Deixo aqui o link para que você mesmo veja como.

Se tratando das inscrições em processo seletivo, estou pensando em criar algo como um novo item no menu "Voluntários" chamado "Processos seletivos", onde serão listados os processos abertos, e a pessoa voluntária pode filtrar por região, tipo de atividade e etc., e também criar um novo item no menu lateral da página do voluntário, onde estejam listados os processos seletivos que ele está inscrito, assim como um link para ver os processos abertos.

E sobre a forma de gerenciar inscrições, talvez um botão ou link chamado "Gerenciar inscrições" em cada processo seletivo, que redirecione para uma página(painel de controle) com uma lista dos voluntários inscritos e suas informações seja uma boa, as entidades podem analisar e revisar as inscrições através dessa página, e talvez até mesmo aceitar ou rejeitar as candidaturas, atualizando o "status" da inscrição, que pode ser usado para informar os candidatos da situação das suas inscrições.

**Comment by regiov** [comment]
Fala @Diogojlq, é bem por aí sim. Esse link novo que você criou pode ir para uma página com a lista de processos seletivos da entidade, permitindo criar um novo processo ou editar um existente (desde que ele ainda não tenha sido publicado). Nessa mesma lista pode estar o outro link que você falou pra poder gerenciar as inscrições de cada processo.

Concordo que é importante criar um novo item no menu principal para consultar processos seletivos em aberto. Mais que isso, na página da entidade também vai ser legal exibir eventuais processos em aberto daquela entidade.

Agora, tem o outro lado também. Imagine um voluntário se inscrevendo em vários processos. Acho importante também ter um link novo no menu lateral dos voluntários pra poder consultar e acompanhar o andamento de cada processo que ele se inscreveu. O menu poderia talvez chamar “inscrições em vagas” (pra não ficar muito comprido).

Fica faltando definir como se dará o gerenciamento das inscrições…

**Comment by regiov** [comment]
Quanto ao formulário, se a entidade criar um formulário no Google forms, imagino que pra gente poder acessar as respostas a entidade vai ter que de alguma forma compartilhar com a gente o formulário. Isso vamos ter que descobrir.

**Comment by Diogojlq** [comment]
Olá Renato, boa tarde.

Eu pesquisei e testei com o Google Forms, e para termos acesso as respostas do formulário a entidade precisa nos dar permissão, e quando tivermos acesso as respostas precisaremos filtrar para cada usuário específico, e aqui tem um ponto de atenção, pois podemos filtrar por email as respostas de cada voluntário para mostrar internamente no site, mas pode ser que o voluntário não utilize o mesmo email no formulário que usou no site, não sei se será um problema também, talvez possamos usar o nome e etc., mas me diga o que acha.

E quanto ao gerenciamento de inscrições acredito que precisemos primeiro definir o que vai ser o gerenciamento, o que a entidade pode fazer com cada candidatura, até agora só pensei em aceitar e rejeitar, e no que isso implicaria para essa candidatura, por exemplo no caso de de estar em análise ainda, podemos mostrar um status em cor amarela para o voluntário com o texto "em análise" e algo semelhante para os casos de aceitação e rejeição.

Devo commitar esses menus "Processos seletivos" e "Inscrições em vagas" juntamente a outras alterações já de agora ? Acho que fica melhor dividir cada pequeno passo em commits diferentes, mas farei como você preferir.

**Comment by regiov** [comment]
Bacana @Diogojlq , e você conseguiu identificar que tipo de permissão é necessária? Espero que não seja nada que nos dê qualquer acesso de escrita.

Também já estava imaginando algumas dificuldades em linkar os candidatos às respostas. Se tiver algum jeito de incluir algum parâmetro no link do formulário que  o candidato vai clicar quando for preencher, e esse parâmetro puder já completar a resposta da pergunta “qual o seu e-mail”, ficaria um pouco mais amarrado. Mas mesmo que não tenha jeito, não vejo esses casos como um problema tão sério. Linkaremos o que for possível.

Sobre o gerenciamento de candidaturas, assim que eu retornar de viagem esse fim de semana vou dar uma ilhada em anotações antigas pra ver se já pensei alguma coisa nesse sentido. 

Sobre os commits, pode ir fazendo sim, mas sugiro que você crie um branch só pra essa issue e fique trabalhando nele. Não lembro se já fiz isso no repo oficial. Penso que no futuro os pull requests devam ser feitos do seu branch para um branch específico no repo oficial, se for possível.

**Comment by Diogojlq** [comment]
Boa noite @regiov.

Sobre a API do Google Forms, veja este texto da própria documentação  :
"Os escopos definem que tipo de dados do usuário você pedirá para acessar em nome do usuário na tela de consentimento".
Pelo que entendi, podemos simplesmente definir que escopo de autorização queremos pedir, então a questão do acesso para escrita não será problema, podemos solicitar apenas as permissões que realmente precisamos, criei uma nova branch para testar um pouco isso tudo. Inclusive, também é possível sim enviar o email como parâmetro na URL e preencher o campo de email automaticamente. Também testarei e pesquisarei mais a fundo como fazer isso.

Fiz um commit agora a pouco e vou fazer alguns outros tentando mantê-los relativamente organizados, dividindo as alterações em pequenas partes.

Parece que agora só falta definir bem os modelos, tem aquela sugestão na wiki, onde o modelo se chamaria "Iniciativa", mas não seria melhor nomeá-lo "Processo Seletivo" ? E o modelo em si, acredito que seja legal colocar aquele campo "noção de área", até mesmo para que o voluntário possa filtrar os processos seletivos por áreas de atuação, mas não tenho certeza se entendi o que você quis dizer com "noção", e estou interpretando que seja um conhecimento desejado por parte da entidade.

**Comment by Diogojlq** [comment]
Olá Renato, gostaria também de te perguntar onde acha que deve ficar o link para página que lista os processos seletivos, tem as listas  "voluntários", "entidades" e "mais" no menu, mas talvez ficasse legal colocar entre "busca de entidades" e "mapa de entidades" um link, mesmo que também coloquemos em um dos menus do site.

**Comment by regiov** [comment]
Salve @Diogojlq, com relação aos modelos, sugiro deixarmos a parte de gerenciamento de projetos/iniciativas pra depois. Vamos manter tudo lá no wiki como forma de registrar as ideias que já tivemos, mas começar implementando a partir de processo seletivo.

Quanto ao menu, concordo que seria legal ficar entre busca de entidades" e "mapa de entidades". Talvez chamar "Processos seletivos" mesmo (?). Vou pensar no modelo de processo seletivo...

**Comment by regiov** [comment]
@Diogojlq fiz um commit com uma proposta inicial de modelo para processo seletivo. Quando puder, veja lá com calma e não se assuste. Achei melhor já fazer algo com máquina de estados, que pra você talvez seja uma novidade (?). Penso inclusive que aos poucos deveríamos adotar máquinas de estados para outras coisas no código. Também fiz alterações no wiki pra incluir um diagrama dessa máquina de estados. Ainda não pensei no gerenciamento das inscrições. Falta inclusive modelo pra isso. Uma observação importante é que o esquema de máquina de estados requer agora duas novas libs que você deve instalar: django-fsm e django-fsm-log. Outra coisa é que o processo seletivo tem um campo slug, que penso em gerarmos algum código único, tipo 375-285-437, ou ab43kP8 (não sei que formato seria melhor). Essa é outra coisa que aos poucos deveríamos fazer para voluntários e entidades, evitando usar números sequenciais em URLs públicas para evitar extração de dados automática por terceiros. Bom, veja o que acha, veja se consegue avançar com base nesse modelo, e qualquer dúvida me avise. Se for o caso podemos inclusive marcar alguma reunião.

**Comment by Diogojlq** [comment]
Boa noite Renato, e novamente desculpe a demora, ainda estou engatando na nova rotina.

Estou lendo sobre máquina de estado e até o momento não me parece muito complicado, mas realmente, pra mim é novidade. Assim que eu puder, provavelmente amanhã de manhã ou de noite, vou fazer alguns commits com o que já foi definido e pensar um pouco sobre como prosseguir e te retorno com eventuais dúvidas.

**Comment by regiov** [comment]
Legal @Diogojlq fiquei preocupado de você ter se assustado muito com esse primeiro modelo… ;-)
Vale a pena aprender sobre máquina de estados. É um recurso poderoso muitas vezes negligenciado ou até desconhecido por muitos desenvolvedores. Por outro lado, outra possibilidade seria você não se preocupar tanto em entender tudo isso nesse momento, pois posso ajudar no que for necessário sem problema algum. A gente só precisa ir coordenando isso entre a gente pra não correr o risco de duplicar trabalho.

Nesse sentido, agora estou me concentrando mais nos modelos mesmo, ok? Se quiser já ir tentando montar outras partes do quebra-cabeça, mesmo sem entender tudo, faça o que você conseguir. Inclusive já tive outras ideias interessantes, mas quero amadurecer um pouco mais antes de comitar. Estou pensando num modelo EtapaDeProcesoSeletivo, que poderia contemplar várias coisas, inclusive o preenchimento de formulário. Ou seja, o campo do link do formulário seria mais adequado nesse novo modelo. Cada processo seletivo seria composto por uma ou mais etapas. Assim que eu ficar melhor (peguei a maldita covid!) dou continuidade a isso.

**Comment by Diogojlq** [comment]
Então @regiov, admito que me causou um certo espanto, mas penso que sempre podemos aprender **qualquer** coisa.

A maior parte do tempo eu passo pensando e pesquisando mesmo, e pode deixar que antes de começar algo novo eu te aviso, pra não acontecer de fazermos a mesma coisa.
Farei também alguns testes com a API do Forms e te passo o que descobrir de relevante.

Desejo melhoras pra você, tenho certeza que logo você estará 100% e estou enviando energias positivas.

**Comment by Diogojlq** [comment]
Bom dia Renato, fiz algumas alterações simples e logo vou criar o modelo e realmente implementar as funcionalidades, criei duas funções que listam processos de uma entidade, me pareceu um pouco redundante mas talvez seja bom ter uma lista que apenas o gestor da entidade tem acesso, e uma onde mostramos apenas os processos em aberto para os candidatos.

**Comment by regiov** [comment]
Opa, obrigado @Diogojlq, também espero melhorar o quanto antes!

Fiz o merge do último PR e acho legal esse esquema de já ir meio que demarcando o que precisa ser implementado. A única coisa que talvez valesse a pena repensar - se você também concordar - seria deixar de ter uma página separada, exclusiva para mostrar os processos seletivos de uma entidade, e já mostrar isso direto na própria página da entidade. Evita um clique a mais, dá mais visibilidade às vagas, e também a página da entidade normalmente nem é tão cheia ainda. O que acha?

**Comment by Diogojlq** [comment]
Boa noite Renato.
Esse esquema me ajuda a "mapear" o código e evitar ficar perdido. Acho uma ótima ideia listar logo de cara, com um "if" que gera uma lista e caso não houverem processos abertos não mostra nada, certo ?

**Comment by regiov** [comment]
Exato, é por aí mesmo. Se não tiver processo talvez seja até melhor dizer alguma coisa do tipo "nenhum processo seletivo em aberto".

**Comment by regiov** [comment]
Oi @Diogojlq só pra avisar que fiz um commit pra completar as definições dos modelos. Nesse fim de semana vou pensar numa mala direta para as entidades pra tentar fazer um levantamento de como cada um faz a seleção de voluntários, pra ver se o esquema que pensei contempla a maioria dos casos. Mas em princípio está tudo lá: processo seletivo (vaga), etapa prevista em processo seletivo, participação em processo seletivo (inscrição) e participação em etapa de processo seletivo. Na medida em que você for avançando, me avise qual a melhor forma de eu ajudar, ok? Assim não corremos risco de duplicar trabalho. Outro detalhe que lembrei com relação àquele mapeamento de alterações que você começou a fazer, é que também vamos precisar criar um menu lateral "processos seletivos", igualzinho já criamos em entidades, mas também para os voluntários, assim eles conseguem acompanhar os processos em que estão participando.

**Comment by Diogojlq** [comment]
Olá @regiov, pode deixar que te aviso sim quando precisar de ajuda, estou criando um senso melhor de quando é improdutivo ficar batendo cabeça e quando vale a pena continuar tentando algo, mas devo dizer, o GPT destrincha problemas que é uma beleza.

Sobre o menu lateral, acredito que tenha eu commitado no último PR, depois me confirma se foi ou não.

**Comment by regiov** [comment]
Tem razão, @Diogojlq, eu que comi bola. Tá lá o menu, sim, acabei de ver. Vi também que você até alterou a página principal, o que tá perfeito. Estou vendo se acho uma imagem pra colocar lá. Então a única coisa que faltou em termos de mapeamento é um link novo na página do painel de controle que vai exibir pro pessoal do adm a qtde de processos seletivos aguardando revisão, pra que eles aprovem por lá. Aí acho que fecha todo o ciclo. Quanto ao chat gpt, se estiver ajudando, ótimo!

**Comment by Diogojlq** [comment]
Bom dia @regiov, esse painel de controle seria na página da entidade, ou você está se referindo á alguma outra página, e o pessoal do adm seriam do próprio coletivo Voluntários ? Se for o segundo caso, onde fica essa página ?

**Comment by regiov** [comment]
Bom dia @Diogojlq, pra você conseguir ver o menu e acessar essa interface, o seu usuário precisa estar marcado com o atributo is_staff verdadeiro. É uma outra página usada pelo pessoal da adm do Voluntários pra fazer todo o trabalho de revisão de cadastros. Em views.py a função chama-se "painel", e o template correspondente é o painel.html.

**Comment by Diogojlq** [comment]
Boa tarde @regiov, e a API do Google Forms ? Ainda vamos usa-lá ? Se sim, como faremos exatamente ?

**Comment by regiov** [comment]
Podemos usar, sim, @Diogojlq, mas é na parte de gerenciamento do processo seletivo através da configuração das etapas. Essa parte talvez seja a mais complicada do conjunto de alterações, e ela tb fica mais para o final, então eu diria pra não se preocupar com isso agora. Tem muita coisa mais simples que já dá pra ir fazendo.

**Comment by regiov** [comment]
@Diogojlq, só pra avisar que tenho feito atualizações no conteúdo do Wiki pra documentar e estruturar melhor as ideias. Inclusive disparei uma mala direta para as entidades mais recentemente cadastradas no site pra entender como elas fazem seus processos seletivos. Coloquei o resultado no Wiki também. Fique à vontade pra mexer no Wiki se quiser. Lembrando que a parte das etapas do processo seletivo é a mais complicada, mas não precisa se preocupar muito com isso agora - posso ajudar na implementação dessa parte. Tem muita coisa que já dá pra ir fazendo sem se preocupar com as etapas.

**Comment by Diogojlq** [comment]
Boa noite @regiov, vou dar uma olhada na Wiki e ver se tem algo que eu possa adicionar.
Estou criando o formulário para criar um processo seletivo, logo abro outro PR com alguns commits envolvendo essa e outras alterações.

**Comment by Diogojlq** [comment]
Boa noite @regiov, fiz alguns commits com mais algumas alterações que acredito serem no caminho certo do planejamento, mas nada muito concreto ainda.

Devo dizer que além de alguns desafios técnicos, estou com muitas demandas pessoais, por isso a demora. Espero nas próximas semanas conseguir retomar o hábito de programar diariamente, e contribuir mais com o projeto.

**Comment by regiov** [comment]
Salve, @Diogojlq! Acabei de fazer o merge. Seus commits estão melhorando bastante. Vou dar uma olhada com calma e talvez fazer só pequenos ajustes. Depois vou tentar fazer o merge de outras alterações que fiz no master pra depois não dar muita diferença. Ansioso pelo dia em que a gente conseguir colocar em produção! Vai ser um evolução bem grande e muito esperada. E depois vem mais coisa boa pela frente pra gente aperfeiçoar ainda mais. Já estou com várias ideias...

**Comment by Diogojlq** [comment]
Coisa linda @regiov, fiz o merge e a migração.

Estou tentando criar um processo seletivo e recebendo um erro que informa que o campo "ProcessoSeletivo.estado" deve ser uma instância, fui analisar pra entender o motivo desse erro, mas me parece que as alterações que você fez não tinham como objetivo já deixar o formulário 100% funcional, estou correto ?

**Comment by regiov** [comment]
Opa, beleza @Diogojlq? Então, eu não cheguei a gravar um processo seletivo, então talvez tenha algum bug sim. Estou longe do computador agora, mas pela mensagem deve ser porque troquei o tipo de campo do formulário tanto do campo estado quanto do campo cidade, que antes acho que já retornavam instâncias e agora retornam ids. Posso ver isso assim que chegar, mas caso queira tentar corrigir acho que é só instanciar estado e cidade a partir dos ids e passar as instâncias no save.

Outra coisa que esqueci de comentar é que talvez você precise rodar o collectstatic pro javascript novo dos combos ficar acessível e funcionar.

**Comment by Diogojlq** [comment]
Boa tarde @regiov, no formulário "ProcessoSeletivo" não seria melhor usar um ModelChoiceField para o estado ? 
Os valores das opções de estado no HTML estão como a sigla("SP","RJ" etc) e não estão retornando o id, sendo que no modelo os campos de estado e cidade são ForeignKeys.

**Comment by regiov** [comment]
Oi @Diogojlq, bom dia! O estado daria pra ser ModelChoiceField, sim. O único problema é que copiei o esquema de atualização do combo de cidade com base no que já estávamos usando nos formulários de entidade e voluntário, cujos modelos ainda estão armazenando sigla do estado e nome da cidade, ao invés dos ids. Para trocar por ModelChoiceField provavelmente será necessário alterar tanto o javascript quanto o views.py. Pessoalmente acho mais fácil por hora a gente instanciar estado e cidade a partir dos parâmetros. No caso da cidade, o problema de usar ModelChoiceField é que o combo vai sempre iniciar carregado com todos os municípios do Brasil, ao passo que do jeito que está, a gente só carrega e atualiza os municípios de acordo com o estado. Bom, vou fazer as alterações, mas qualquer coisa a gente melhora o código depois, sem problema.

**Comment by Diogojlq** [comment]
Boa tarde @regiov, acabei de fazer alguns testes manuais das novas alterações, tudo está correndo perfeitamente até onde pude testar. Só consegui testar até o ponto onde o voluntário se inscreve na vaga, na wiki você colocou definiu como se seguirá porém não encontrei no código as etapas além deste ponto, são especificações ainda a serem implementadas ?

**Comment by regiov** [comment]
Oi @Diogojlq , legal que conseguiu testar. Você consegue ir além desse ponto sim. A inscrição na vaga é o ponto final para o voluntário, mas o processo seletivo continua acessando o sistema como entidade e clicando no numero de inscritos. O teste completo é um pouco intrincado, por ter que alternar usuários (voluntário/entidade) e considerar todos os caminhos possíveis. Imagino que você tenha atualizado o banco gerando a migração. Outra coisa é que existem algumas  mensagens automáticas ao longo do processo, com mensagens novas que precisam ser incluídas no banco (fixture notification.Message). Além disso algumas passagens de status acontecem via linha de comando que será colocado em cron no servidor, mas pode ser rodado manualmente em testes. O lance é conseguir levar um processo seletivo por todos os status até o fim.

**Comment by Diogojlq** [comment]
Olá @regiov, acredito que eu tenha feito todos os caminhos possíveis no processo, testei com mais de um inscrito, testei selecionando e não selecionando os candidatos, enfim, acredito que esteja tudo certo, qualquer coisa é só dizer.
Algo que acredito que poderíamos melhorar é a forma de acessar a lista de candidatos inscritos no processo, colocar algo que fique mais óbvio, como um botão ou um link.

**Comment by regiov** [comment]
Legal @Diogojlq, muito obrigado pelos testes! Concordo que o link para a lista de candidatos estava bem discreto. Acabei de incluir um botão ao lado do número. Duas coisas que me preocupam ainda é a página da vaga, que pra mim está muito sem graça em termos visuais, e o fato do voluntário ter que esperar sua aprovação de cadastro pra poder se inscrever numa vaga. Fora isso, também quero fazer mais uma sessão de testes por aqui e depois preciso alinhar com o pessoal do administrativo essas novas funcionalidades antes de pensar em colocar no ar.

**Comment by Diogojlq** [comment]
@regiov tem alguma sugestão do que pode ser feito para a página ficar mais interessante ?

**Comment by regiov** [comment]
@Diogojlq não tive tempo de ver com mais calma, mas aceito sugestões. Talvez dar uma olhada na “concorrência”, sei lá. Quero ver se esse fim de semana implemento um contador de visualizações de cada vaga, pra gente monitorar quantas pessoas estão vendo. Outra coisa que acho que vai ser bem legal implementar num futuro próximo é uma espécie de “carrinho de compra” que a entidade possa procurar voluntários e ir colocando nesse “carrinho” da vaga pra depois enviar um convite para os voluntários olharem a vaga e ver se eles se interessam em se inscrever. Mas ainda não sei bem como seria isso na prática. No futuro seria legal inclusive permitir que os próprios voluntários indiquem a vaga a outros voluntários. Coisas pra se pensar…

**Comment by regiov** [comment]
@Diogojlq tentei melhorar um pouco a página de exibição de vaga, seguindo o padrão da página de exibição de entidade. Acrescentei um campo importante que faltava lá tb. Implementei a contagem de visualizações e corrigi um erro grave de url. Acho que agora está tudo ok da parte técnica pra colocar no ar, mas preciso alinhar com o pessoal administrativo antes. Estamos planejando uma reunião geral em breve. Talvez lançar depois disso...

**Comment by Diogojlq** [comment]
Muito bem, em relação a ideia do "carrinho de compras", achei muito interessante, será que rola de implementar antes de colocar no ar ? Ou já devo começar a escolher uma nova issue para trabalhar ?

**Comment by regiov** [comment]
@Diogojlq, qualquer issue que você se disponha a ajudar será ótimo. Essa ideia do carrinho talvez seja um pouco difícil por envolver várias coisas (front-end com ajax, backend, envio de e-mails...), mas se quiser tentar, fica a seu critério. Só não acho que devemos criar expectativa de já incorporar isso no lançamento das vagas. De qualquer forma tomei a liberdade de já criar uma issue específica pra isso já com algumas ideias (issue #75). Essa issue na verdade vai se beneficiar muito da issue #74 que pode ser implementada separadamente antes e juntada ao código master, pois independe de vagas. Talvez fosse interessante você iniciar pela #74? Seja qual for a decisão, podemos continuar nos comentários da issue que você escolher...
