### ISSUE TITLE
Exibir CNPJ na página da entidade

### ISSUE THREAD

**Issue by regiov** [regiov/voluntarios#18]
Talvez também exibir link para cartão de CNPJ, se tiver.

**Comment by igoraserpac** [comment]
Essa issue ainda está disponível?

**Comment by regiov** [comment]
Está sim, @igoraserpac. Fique à vontade pra trabalhar nela. Podíamos tentar usar o recurso "assignee", no topo do menu aqui ao lado, pra indicar se tem alguém já trabalhando na issue. Nunca usei esse recurso. Você consegue atribuir a issue pra você?

**Comment by regiov** [comment]
Sobre essa issue, acrescento os seguintes detalhes:
* Nem todas as entidades no banco de produção possuem CNPJ cadastrado (são entidades antigas, importadas do banco anterior).
* Nem todos os CNPJs cadastrados são válidos. Use o método "cnpj_valido" do modelo entidade pra verificar.
* Acho que somente devemos exibir o label/campo CNPJ se houver CNPJ e se ele for válido.

**Comment by igoraserpac** [comment]
> Você consegue atribuir a issue pra você?

Vou começar a trabalhar nela hoje, porém acho que apenas pessoas com permissões de gravação no repositório e integrantes da organização com permissões de leitura no repositório podem associar a issue à alguém, veja se consegue associar ela a mim seguindo [esse tutorial](https://docs.github.com/pt/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users).

**Comment by igoraserpac** [comment]
> Sobre essa issue, acrescento os seguintes detalhes:
> 
> * Nem todas as entidades no banco de produção possuem CNPJ cadastrado (são entidades antigas, importadas do banco anterior).
> * Nem todos os CNPJs cadastrados são válidos. Use o método "cnpj_valido" do modelo entidade pra verificar.
> * Acho que somente devemos exibir o label/campo CNPJ se houver CNPJ e se ele for válido.

Certo, tentarei fazer desta forma.
