### ISSUE TITLE
Trocar uso do django-bootstrap-form pelo django-crispy-forms

### ISSUE THREAD

**Issue by regiov** [regiov/voluntarios#20]
O django-bootstrap-form não é compatível com versões mais recentes do bootstrap, e o projeto parece estar abandonado. O django-bootstrap-form está sendo usado nas páginas customizadas do django-allauth (ex: login.html, pasword_change.html...). Os templates que usam o django-bootstrap-form caracterizam-se por usar {% load bootstrap %} e {{ form|bootstrap }}.
O django-crispy-forms segue o mesmo padrão, sendo necessário usar: {% load crispy_forms_tags %} e depois {{ form|crispy }}, mas resta saber se funciona com bootstrap 5!

**Comment by regiov** [comment]
@igoraserpac eu estava olhando as issues e talvez seja necessário resolver essa daqui antes de fazer a atualização do bootstrap...

**Comment by igoraserpac** [comment]
@regiov show, vou fazer essa alteração junto com o Login do Google.
