### ISSUE TITLE
Atualizar logotipo do Twitter

### ISSUE THREAD

**Issue by regiov** [regiov/voluntarios#65]
Tem no rodapé de todas as páginas (base.html), no final de cada postagem no blog (postagem_blog.html) e tem na página das entidades (exibe_entidade.html).

**Comment by rebecaaras** [comment]
Fiz um pull request para resolver esta issue.

**Comment by regiov** [comment]
Que legal, @rebecaaras! Você não chegou a testar sem a versão antiga pra gente ver se pode remover ela do header? O site usa vários ícones do font-awesome. O ideal seria um dia a gente ter algum teste automatizado onde pudéssemos colocar todos os ícones que usamos pra ver se ao atualizar a versão continua tudo funcionando. Coisas pra se pensar...

**Comment by regiov** [comment]
Já testei sem os links da versão antiga. Aparentemente tudo OK. Já vai pro ar...

**Comment by rebecaaras** [comment]
> Que legal, @rebecaaras! Você não chegou a testar sem a versão antiga pra gente ver se pode remover ela do header? O site usa vários ícones do font-awesome. O ideal seria um dia a gente ter algum teste automatizado onde pudéssemos colocar todos os ícones que usamos pra ver se ao atualizar a versão continua tudo funcionando. Coisas pra se pensar...

Não pensei na hora em remover o link com o fontawesome antigo. Bom que deu certo!
