### ISSUE TITLE
Criar página com perguntas & respostas

### ISSUE THREAD

**Issue by regiov** [regiov/voluntarios#7]

**Comment by Diogojlq** [comment]
Vou trabalhar nessa issue !!

**Comment by regiov** [comment]
Legal, @Diogojlq, existem várias formas de implementar essa issue. Penso que a mais fácil seja criar uma página "estática" mesmo. Existem várias no site. Para criar ou editar essas páginas é preciso conseguir acessar a interface administrativa. Lá tem uma seção "páginas estáticas" onde você consegue criar uma nova "página plana". Depois terá que criar um link para ela no menu principal do site (ver template base.html). Creio que faça mais sentido isso ficar no menu "Mais". Quanto ao conteúdo, não temos nada pronto. Quer tentar pensar no conteúdo também? Uma primeira fonte de informação pra isso é nossa cartilha de voluntariado. Ela pode ser baixada da página principal do site.

**Comment by Diogojlq** [comment]
Criei a página e o link para ela no menu, mas estou com uma dúvida para fazer o commit.
A página está salva na tabela "django_flatpage" , criei um arquivo csv para incluir no commit juntamente as alterações que fiz no arquivo "base.html" em "website/vol/templates/vol/base.html".
Tem alguma forma diferente de fazer esse commit, ou eu envio esse csv para que você possa popular o banco com ele ?

**Comment by regiov** [comment]
Sim, tem uma forma diferente. Caso você tenha seguido as instruções de instalação, deve ter carregado as fixtures do banco, incluindo as páginas planas usadas pelo site. Ou seja, imagino que ao acessar a interface adm você tenha se deparado com algumas páginas pré existentes, correto? Neste caso, pode sobrepor as fixtures padrão incluindo a nova página:

python3 manage.py dumpdata flatpages.FlatPage > vol/fixtures/django_flatpage.json

Depois é só incluir esse arquivo json no commit e fazer o pull request...
